# Generated by Django 4.0.5 on 2023-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='img_vid',
            field=models.ImageField(default='', upload_to='media/post/'),
        ),
    ]
