# Generated by Django 4.0.5 on 2023-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0003_friendsmodal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsmodal',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendsmodal',
            name='friendReqSendTo',
            field=models.ManyToManyField(blank=True, related_name='friendReqRecieveBy', to='createcontent.friendsmodal'),
        ),
    ]
