# Generated by Django 4.0.5 on 2023-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0004_remove_friendsmodal_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendsmodal',
            name='friendReqSendTo',
        ),
        migrations.AddField(
            model_name='friendsmodal',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='createcontent.friendsmodal'),
        ),
    ]
