# Generated by Django 4.0.5 on 2023-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0009_dopost_delete_doinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentCounter',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
