# Generated by Django 4.0.5 on 2023-01-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0010_post_commentcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='commentCounter',
        ),
        migrations.DeleteModel(
            name='DoPOST',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='createcontent.comment'),
            preserve_default=False,
        ),
    ]
