# Generated by Django 4.0.5 on 2023-01-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0011_comment_remove_post_commentcounter_delete_dopost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
