# Generated by Django 4.0.5 on 2023-01-29 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0018_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
