# Generated by Django 4.0.5 on 2023-01-29 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0019_dopost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopost',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
