# Generated by Django 4.0.5 on 2023-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontent', '0021_alter_dopost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopost',
            name='comments',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dopost',
            name='commentsUsername',
            field=models.CharField(default='admin', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='share',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
