# Generated by Django 4.0.5 on 2023-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
    ]
