# Generated by Django 4.0.5 on 2023-01-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fModal',
        ),
    ]
